# CHAPTER 3

# Machine Learning for Classification

###  3.1 Churn prediction project
____

* Dataset: https://www.kaggle.com/blastchar/telco-customer-churn

###   3.2 Churn prediction project
____


* Download the data, read it with pandas
* Look at the data
* Make column names and values look uniform
* Check if all the columns read correctly
* Check if the churn variable needs any preparation

In [310]:
import pandas as pd
import numpy as np
 
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [311]:
df = pd.read_csv('data-week-3.csv')

In [312]:
# checking the length of the data
len(df)

7043

In [313]:
# checking the shape of the data
df.shape

(7043, 21)

In [314]:
# checking the first 5 rows of the data
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [315]:
# transposing the data for  better view
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU,9305-CDSKC,1452-KIOVK,6713-OKOMC,7892-POOKP,6388-TABGU,...,9767-FFLEM,0639-TSIQW,8456-QDAVC,7750-EYXWZ,2569-WGERO,6840-RESVB,2234-XADUH,4801-JZAZL,8361-LTMKD,3186-AJIEK
gender,Female,Male,Male,Male,Female,Female,Male,Female,Female,Male,...,Male,Female,Male,Female,Female,Male,Female,Female,Male,Male
SeniorCitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Partner,Yes,No,No,No,No,No,No,No,Yes,No,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No
Dependents,No,No,No,No,No,No,Yes,No,No,Yes,...,No,No,No,No,No,Yes,Yes,Yes,No,No
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
PhoneService,No,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Yes,...,Yes,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Yes
MultipleLines,No phone service,No,No,No phone service,No,Yes,Yes,No phone service,Yes,No,...,No,Yes,No,No phone service,No,Yes,Yes,No phone service,Yes,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic,Fiber optic,Fiber optic,DSL,Fiber optic,DSL,...,Fiber optic,Fiber optic,Fiber optic,DSL,No,DSL,Fiber optic,DSL,Fiber optic,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No,No,No,Yes,No,Yes,...,No,Yes,No,No,No internet service,Yes,No,Yes,No,Yes
OnlineBackup,Yes,No,Yes,No,No,No,Yes,No,No,Yes,...,No,Yes,No,Yes,No internet service,No,Yes,No,No,No
DeviceProtection,No,Yes,No,Yes,No,Yes,No,No,Yes,No,...,No,Yes,No,Yes,No internet service,Yes,Yes,No,No,Yes
TechSupport,No,No,No,Yes,No,No,No,No,Yes,No,...,No,No,No,Yes,No internet service,Yes,No,No,No,Yes
StreamingTV,No,No,No,No,No,Yes,Yes,No,Yes,No,...,No,Yes,Yes,Yes,No internet service,Yes,Yes,No,No,Yes
StreamingMovies,No,No,No,No,No,Yes,No,No,Yes,No,...,No,No,No,Yes,No internet service,Yes,Yes,No,No,Yes
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month,Month-to-month,Month-to-month,Month-to-month,Month-to-month,One year,...,Month-to-month,Month-to-month,Month-to-month,One year,Two year,One year,One year,Month-to-month,Month-to-month,Two year
PaperlessBilling,Yes,No,Yes,No,Yes,Yes,Yes,No,Yes,No,...,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check,Electronic check,Credit card (automatic),Mailed check,Electronic check,Bank transfer (automatic),...,Credit card (automatic),Credit card (automatic),Bank transfer (automatic),Electronic check,Bank transfer (automatic),Mailed check,Credit card (automatic),Electronic check,Mailed check,Bank transfer (automatic)
MonthlyCharges,29.85,56.95,53.85,42.3,70.7,99.65,89.1,29.75,104.8,56.15,...,69.5,102.95,78.7,60.65,21.15,84.8,103.2,29.6,74.4,105.65
TotalCharges,29.85,1889.5,108.15,1840.75,151.65,820.5,1949.4,301.9,3046.05,3487.95,...,2625.25,6886.25,1495.1,743.3,1419.4,1990.5,7362.9,346.45,306.6,6844.5
Churn,No,No,Yes,No,Yes,Yes,No,No,Yes,No,...,No,Yes,No,No,No,No,No,No,Yes,No

In [316]:
# checking the data types of the columns
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [317]:
# we force the TotalCharges column to be numeric
total_charges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.TotalCharges = total_charges
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [318]:
df[total_charges.isnull()][['customerID', 'TotalCharges']]

      customerID  TotalCharges
488   4472-LVYGI           NaN
753   3115-CZMZD           NaN
936   5709-LVOEQ           NaN
1082  4367-NUYAO           NaN
1340  1371-DWPAZ           NaN
3331  7644-OMVMY           NaN
3826  3213-VVOLG           NaN
4380  2520-SGTTA           NaN
5218  2923-ARZLG           NaN
6670  4075-WKNIU           NaN
6754  2775-SEFEE           NaN

In [319]:
# checkig the number of missing values
df.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [320]:
# filling the missing values with 0
df['TotalCharges'] = df.TotalCharges.fillna(0)
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [321]:
# clean the column headers 
def clean_column_header(df):
    df.columns = df.columns.astype(str)
    df.columns = df.columns.str.strip()
    df.columns = df.columns.str.lower()
    df.columns = df.columns.str.replace( ' ', '_')
    return df

# calling the function 
clean_column_header(df)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [322]:
# checking the content of the changes to the columnn header
# this can be easily seen with the df being transpose
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerid,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU,9305-CDSKC,1452-KIOVK,6713-OKOMC,7892-POOKP,6388-TABGU,...,9767-FFLEM,0639-TSIQW,8456-QDAVC,7750-EYXWZ,2569-WGERO,6840-RESVB,2234-XADUH,4801-JZAZL,8361-LTMKD,3186-AJIEK
gender,Female,Male,Male,Male,Female,Female,Male,Female,Female,Male,...,Male,Female,Male,Female,Female,Male,Female,Female,Male,Male
seniorcitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
partner,Yes,No,No,No,No,No,No,No,Yes,No,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No
dependents,No,No,No,No,No,No,Yes,No,No,Yes,...,No,No,No,No,No,Yes,Yes,Yes,No,No
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
phoneservice,No,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Yes,...,Yes,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Yes
multiplelines,No phone service,No,No,No phone service,No,Yes,Yes,No phone service,Yes,No,...,No,Yes,No,No phone service,No,Yes,Yes,No phone service,Yes,No
internetservice,DSL,DSL,DSL,DSL,Fiber optic,Fiber optic,Fiber optic,DSL,Fiber optic,DSL,...,Fiber optic,Fiber optic,Fiber optic,DSL,No,DSL,Fiber optic,DSL,Fiber optic,Fiber optic
onlinesecurity,No,Yes,Yes,Yes,No,No,No,Yes,No,Yes,...,No,Yes,No,No,No internet service,Yes,No,Yes,No,Yes
onlinebackup,Yes,No,Yes,No,No,No,Yes,No,No,Yes,...,No,Yes,No,Yes,No internet service,No,Yes,No,No,No
deviceprotection,No,Yes,No,Yes,No,Yes,No,No,Yes,No,...,No,Yes,No,Yes,No internet service,Yes,Yes,No,No,Yes
techsupport,No,No,No,Yes,No,No,No,No,Yes,No,...,No,No,No,Yes,No internet service,Yes,No,No,No,Yes
streamingtv,No,No,No,No,No,Yes,Yes,No,Yes,No,...,No,Yes,Yes,Yes,No internet service,Yes,Yes,No,No,Yes
streamingmovies,No,No,No,No,No,Yes,No,No,Yes,No,...,No,No,No,Yes,No internet service,Yes,Yes,No,No,Yes
contract,Month-to-month,One year,Month-to-month,One year,Month-to-month,Month-to-month,Month-to-month,Month-to-month,Month-to-month,One year,...,Month-to-month,Month-to-month,Month-to-month,One year,Two year,One year,One year,Month-to-month,Month-to-month,Two year
paperlessbilling,Yes,No,Yes,No,Yes,Yes,Yes,No,Yes,No,...,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes
paymentmethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check,Electronic check,Credit card (automatic),Mailed check,Electronic check,Bank transfer (automatic),...,Credit card (automatic),Credit card (automatic),Bank transfer (automatic),Electronic check,Bank transfer (automatic),Mailed check,Credit card (automatic),Electronic check,Mailed check,Bank transfer (automatic)
monthlycharges,29.85,56.95,53.85,42.3,70.7,99.65,89.1,29.75,104.8,56.15,...,69.5,102.95,78.7,60.65,21.15,84.8,103.2,29.6,74.4,105.65
totalcharges,29.85,1889.5,108.15,1840.75,151.65,820.5,1949.4,301.9,3046.05,3487.95,...,2625.25,6886.25,1495.1,743.3,1419.4,1990.5,7362.9,346.45,306.6,6844.5
churn,No,No,Yes,No,Yes,Yes,No,No,Yes,No,...,No,Yes,No,No,No,No,No,No,Yes,No

In [323]:
# channging the column context which are object to uniform content
object_columns_content = df.select_dtypes(include='object')
object_columns_content

,customerid,gender,partner,dependents,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,churn
0,7590-VHVEG,Female,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,No
1,5575-GNVDE,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,No
2,3668-QPYBK,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,Yes
3,7795-CFOCW,Male,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),No
4,9237-HQITU,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,No
7039,2234-XADUH,Female,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),No
7040,4801-JZAZL,Female,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,No
7041,8361-LTMKD,Male,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,Yes
7042,3186-AJIEK,Male,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),No

In [324]:
# transforming those columns to uniform content 
def clean_column_content(df, column_name):
    df[column_name] = df[column_name].astype(str)
    df[column_name] = df[column_name].str.lower()
    df[column_name] = df[column_name].str.replace(' ', '_')
    return df

for col in object_columns_content:
    clean_categorical_data_for_use = clean_column_content(df, col)
    
df

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,no
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.50,no
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,yes
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-resvb,male,0,yes,yes,24,yes,yes,dsl,yes,...,yes,yes,yes,yes,one_year,yes,mailed_check,84.80,1990.50,no
7039,2234-xaduh,female,0,yes,yes,72,yes,yes,fiber_optic,no,...,yes,no,yes,yes,one_year,yes,credit_card_(automatic),103.20,7362.90,no
7040,4801-jzazl,female,0,yes,yes,11,no,no_phone_service,dsl,yes,...,no,no,no,no,month-to-month,yes,electronic_check,29.60,346.45,no
7041,8361-ltmkd,male,1,yes,no,4,yes,yes,fiber_optic,no,...,no,no,no,no,month-to-month,yes,mailed_check,74.40,306.60,yes
7042,3186-ajiek,male,0,no,no,66,yes,no,fiber_optic,yes,...,yes,yes,yes,yes,two_year,yes,bank_transfer_(automatic),105.65,6844.50,no

In [325]:
# checking the target variables 
df['churn'].value_counts()

churn
no     5174
yes    1869
Name: count, dtype: int64

In [326]:
# checking the target variables before encoding
df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: object

In [327]:
# converting the target column to binary
df.churn = (df.churn == 'yes').astype(int)

In [328]:
df.churn.head()

0    0
1    0
2    1
3    0
4    1
Name: churn, dtype: int64

In [329]:
df

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,0
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.50,0
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,1
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,0
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-resvb,male,0,yes,yes,24,yes,yes,dsl,yes,...,yes,yes,yes,yes,one_year,yes,mailed_check,84.80,1990.50,0
7039,2234-xaduh,female,0,yes,yes,72,yes,yes,fiber_optic,no,...,yes,no,yes,yes,one_year,yes,credit_card_(automatic),103.20,7362.90,0
7040,4801-jzazl,female,0,yes,yes,11,no,no_phone_service,dsl,yes,...,no,no,no,no,month-to-month,yes,electronic_check,29.60,346.45,0
7041,8361-ltmkd,male,1,yes,no,4,yes,yes,fiber_optic,no,...,no,no,no,no,month-to-month,yes,mailed_check,74.40,306.60,1
7042,3186-ajiek,male,0,no,no,66,yes,no,fiber_optic,yes,...,yes,yes,yes,yes,two_year,yes,bank_transfer_(automatic),105.65,6844.50,0

### 3.3 Setting up the validation framework
____

* Perform the train/validation/test split with Scikit-Learn


- The df_train_full data is already split into train and test of 80% and 20% respectively/ 

- We will split the df_train_full data into train and validation.

In [330]:
# importing the model for data splitting
from sklearn.model_selection import train_test_split

In [331]:
# splitting the data into training and testing
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=1)


# splitting the training data into training and validation
df_train, df_val = train_test_split(df_train_full, test_size=0.25, random_state=11)

In [332]:
# checking the length of the data
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [333]:
# reseting the index after splitting 
df_train_full = df_train_full.reset_index(drop=True)
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [334]:
# assigning the target variables to the y_train and y_val
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [335]:
# deleting the target variables from the data
del df_train['churn']
del df_val['churn']
del df_test['churn']

###  3.4 Exploratory data analysis
____

In [336]:
# checking the data for missing values
df_train_full.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [337]:
# checking the distribution of the target variables
df_train_full.churn.value_counts()

churn
0    4113
1    1521
Name: count, dtype: int64

In [338]:
# nornalizing the data
df_train_full.churn.value_counts(normalize=True)

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

In [339]:
# calculating the probability of churn rate direct 
global_mean = df_train_full.churn.mean()

# rounding the result to 3 decimal 
round(global_mean, 3)

0.27

In [340]:
# creating the numerical and categgorical variables 
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
               'phoneservice', 'multiplelines', 'internetservice',
               'onlinesecurity', 'onlinebackup', 'deviceprotection',
               'techsupport', 'streamingtv', 'streamingmovies',
               'contract', 'paperlessbilling', 'paymentmethod']
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [341]:
# list of all categorical columns
categorical

['gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod']

#### 3.5 Feature importance: Churn rate and ratios
____

Feature importance analysis (part of EDA) - identifying which features affect our target variable

* Churn rate
* Risk ratio
* Mutual information

In [342]:
# checking the number of unique values in the categorical columns
df_train_full[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [343]:
df_train_full[categorical]['gender']

0         male
1       female
2         male
3         male
4         male
         ...
5629      male
5630      male
5631      male
5632      male
5633    female
Name: gender, Length: 5634, dtype: object

In [344]:
# calculating the mean of the churn rate for categorical columns

female_mean = df_train_full[df_train_full.gender == 'female'].churn.mean()


print('female_mean:', round(female_mean, 3))

female_mean: 0.277

In [345]:
# calculating the mean of the churn rate for categorical columns
male_mean = df_train_full[df_train_full.gender == 'male'].churn.mean()

print('male_mean:', round(male_mean, 3))

male_mean: 0.263

In [346]:
# calculating the mean of the churn rate for categorical columns

partner_yes = df_train_full[df_train_full.partner == 'yes'].churn.mean()


print('partners == yes:', round(partner_yes, 3))

partners == yes: 0.205

In [347]:
# calculating the mean of the churn rate for categorical columns

partner_no = df_train_full[df_train_full[categorical]['partner'] == 'no'].churn.mean()


print('partners == yes:', round(partner_no, 3))

partners == yes: 0.33

In [348]:
# ceating a function to calculate the mean of the churn rate for categorical columns

global_mean = df_train_full.churn.mean()
 
df_group = df_train_full.groupby(by='gender').churn.agg(['mean'])
df_group['diff'] = df_group['mean'] - global_mean
df_group['risk'] = df_group['mean'] / global_mean
 
df_group

            mean      diff      risk
gender
female  0.276824  0.006856  1.025396
male    0.263214 -0.006755  0.974980

In [349]:
# ceating a function to calculate the mean of the churn rate for categorical columns with display

from IPython.display import display 
 
for col in categorical:
    df_group = df_train_full.groupby(by=col).churn.agg(['mean'])
    df_group['diff'] = df_group['mean'] - global_mean
    df_group['rate'] = df_group['mean'] / global_mean
    display(df_group)

            mean      diff      rate
gender
female  0.276824  0.006856  1.025396
male    0.263214 -0.006755  0.974980

                   mean      diff      rate
seniorcitizen
0              0.242270 -0.027698  0.897403
1              0.413377  0.143409  1.531208

             mean      diff      rate
partner
no       0.329809  0.059841  1.221659
yes      0.205033 -0.064935  0.759472

                mean      diff      rate
dependents
no          0.313760  0.043792  1.162212
yes         0.165666 -0.104302  0.613651

                  mean      diff      rate
phoneservice
no            0.241316 -0.028652  0.893870
yes           0.273049  0.003081  1.011412

                      mean      diff      rate
multiplelines
no                0.257407 -0.012561  0.953474
no_phone_service  0.241316 -0.028652  0.893870
yes               0.290742  0.020773  1.076948

                     mean      diff      rate
internetservice
dsl              0.192347 -0.077621  0.712482
fiber_optic      0.425171  0.155203  1.574895
no               0.077805 -0.192163  0.288201

                         mean      diff      rate
onlinesecurity
no                   0.420921  0.150953  1.559152
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.153226 -0.116742  0.567570

                         mean      diff      rate
onlinebackup
no                   0.404323  0.134355  1.497672
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.217232 -0.052736  0.804660

                         mean      diff      rate
deviceprotection
no                   0.395875  0.125907  1.466379
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.230412 -0.039556  0.853480

                         mean      diff      rate
techsupport
no                   0.418914  0.148946  1.551717
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.159926 -0.110042  0.592390

                         mean      diff      rate
streamingtv
no                   0.342832  0.072864  1.269897
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.302723  0.032755  1.121328

                         mean      diff      rate
streamingmovies
no                   0.338906  0.068938  1.255358
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.307273  0.037305  1.138182

                    mean      diff      rate
contract
month-to-month  0.431701  0.161733  1.599082
one_year        0.120573 -0.149395  0.446621
two_year        0.028274 -0.241694  0.104730

                      mean      diff      rate
paperlessbilling
no                0.172071 -0.097897  0.637375
yes               0.338151  0.068183  1.252560

                               mean      diff      rate
paymentmethod
bank_transfer_(automatic)  0.168171 -0.101797  0.622928
credit_card_(automatic)    0.164339 -0.105630  0.608733
electronic_check           0.455890  0.185922  1.688682
mailed_check               0.193870 -0.076098  0.718121

####  3.6 Feature importance: Mutual information
___

In [350]:
from sklearn.metrics import mutual_info_score

In [351]:
mutual_info_score(df_train_full.churn, df_train_full.contract)

0.0983203874041556

In [352]:
# mutual info score between churn and onlniebackup
mutual_info_score(df_train_full.churn, df_train_full.onlinebackup)

0.0469234640537918

In [353]:
# mutual info score between churn and gender
mutual_info_score(df_train_full.gender, df_train_full.churn)

0.0001174846211139946

In [354]:
# mutual info score between churn and contract (val)
mutual_info_score(df_train_full.contract, df_train_full.churn)

0.0983203874041556

In [355]:
# mutual info score between churn and partner
mutual_info_score(df_train_full.partner, df_train_full.churn)

0.009967689095399745

Creating a function to calculate mutual information between categorical variables and the target variable

In [356]:
# mutual info score function  between churn and dependents
def calculate_mi(series):
    return mutual_info_score(series, df_train_full.churn)



# calculate mutual info score for all categorical columns
mi = df_train_full[categorical].apply(calculate_mi)
mi.sort_values(ascending=False)

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64

#### 3.7 Feature importance: Correlation
____

In [357]:
df_train_full[numerical].corrwith(df_train_full.churn).abs()

tenure            0.351885
monthlycharges    0.196805
totalcharges      0.196353
dtype: float64

#### 3.8 One-hot encoding
____

In [358]:
from sklearn.feature_extraction import DictVectorizer

In [359]:
# Initialize DictVectorizer
dv = DictVectorizer(sparse=False)


# Convert DataFrame to list of dictionaries
train_dict = df_train[categorical + numerical].to_dict(orient='records')
val_dict =  df_val[categorical + numerical].to_dict(orient='records')


# Transform the list of dictionaries into a matrix
X_train = dv.fit_transform(train_dict)
X_val = dv.transform(val_dict)


# # Get feature names
feature_names = dv.get_feature_names_out()

# Display the encoded matrix and feature names
print(pd.DataFrame(X_train, columns=feature_names))

      contract=month-to-month  contract=one_year  contract=two_year  \
0                         0.0                1.0                0.0
1                         1.0                0.0                0.0
2                         0.0                0.0                1.0
3                         1.0                0.0                0.0
4                         1.0                0.0                0.0
...                       ...                ...                ...
4220                      0.0                0.0                1.0
4221                      1.0                0.0                0.0
4222                      0.0                1.0                0.0
4223                      1.0                0.0                0.0
4224                      1.0                0.0                0.0

      dependents=no  dependents=yes  deviceprotection=no  \
0               0.0             1.0                  0.0
1               1.0             0.0                  1.0
2               0.0             1.0                  0.0
3               1.0             0.0                  1.0
4               1.0             0.0                  0.0
...             ...             ...                  ...
4220            1.0             0.0                  0.0
4221            1.0             0.0                  1.0
4222            1.0             0.0                  0.0
4223            1.0             0.0                  0.0
4224            0.0             1.0                  1.0

      deviceprotection=no_internet_service  deviceprotection=yes  \
0                                      0.0                   1.0
1                                      0.0                   0.0
2                                      1.0                   0.0
3                                      0.0                   0.0
4                                      0.0                   1.0
...                                    ...                   ...
4220                                   0.0                   1.0
4221                                   0.0                   0.0
4222                                   1.0                   0.0
4223                                   1.0                   0.0
4224                                   0.0                   0.0

      gender=female  gender=male  ...  streamingmovies=no_internet_service  \
0               1.0          0.0  ...                                  0.0
1               1.0          0.0  ...                                  0.0
2               0.0          1.0  ...                                  1.0
3               1.0          0.0  ...                                  0.0
4               1.0          0.0  ...                                  0.0
...             ...          ...  ...                                  ...
4220            0.0          1.0  ...                                  0.0
4221            1.0          0.0  ...                                  0.0
4222            0.0          1.0  ...                                  1.0
4223            1.0          0.0  ...                                  1.0
4224            1.0          0.0  ...                                  0.0

      streamingmovies=yes  streamingtv=no  streamingtv=no_internet_service  \
0                     1.0             0.0                              0.0
1                     0.0             0.0                              0.0
2                     0.0             0.0                              1.0
3                     0.0             1.0                              0.0
4                     1.0             1.0                              0.0
...                   ...             ...                              ...
4220                  1.0             0.0                              0.0
4221                  0.0             1.0                              0.0
4222                  0.0             0.0                              1.0
4223                  0.0             0.0                              1.0
4224                  0.0             1.0                              0.0

      streamingtv=yes  techsupport=no  techsupport=no_internet_service  \
0                 1.0             1.0                              0.0
1                 1.0             1.0                              0.0
2                 0.0             0.0                              1.0
3                 0.0             1.0                              0.0
4                 0.0             1.0                              0.0
...               ...             ...                              ...
4220              1.0             0.0                              0.0
4221              0.0             1.0                              0.0
4222              0.0             0.0                              1.0
4223              0.0             0.0                              1.0
4224              0.0             0.0                              0.0

      techsupport=yes  tenure  totalcharges
0                 0.0    58.0       6225.40
1                 0.0    16.0       1378.25
2                 0.0    71.0       1378.45
3                 0.0     5.0        318.50
4                 0.0    47.0       4045.65
...               ...     ...           ...
4220              1.0    63.0       6705.70
4221              0.0     2.0        142.35
4222              0.0     2.0         28.30
4223              0.0    23.0        470.60
4224              1.0    64.0       5327.25

[4225 rows x 45 columns]

In [360]:
list(feature_names)

['contract=month-to-month',
 'contract=one_year',
 'contract=two_year',
 'dependents=no',
 'dependents=yes',
 'deviceprotection=no',
 'deviceprotection=no_internet_service',
 'deviceprotection=yes',
 'gender=female',
 'gender=male',
 'internetservice=dsl',
 'internetservice=fiber_optic',
 'internetservice=no',
 'monthlycharges',
 'multiplelines=no',
 'multiplelines=no_phone_service',
 'multiplelines=yes',
 'onlinebackup=no',
 'onlinebackup=no_internet_service',
 'onlinebackup=yes',
 'onlinesecurity=no',
 'onlinesecurity=no_internet_service',
 'onlinesecurity=yes',
 'paperlessbilling=no',
 'paperlessbilling=yes',
 'partner=no',
 'partner=yes',
 'paymentmethod=bank_transfer_(automatic)',
 'paymentmethod=credit_card_(automatic)',
 'paymentmethod=electronic_check',
 'paymentmethod=mailed_check',
 'phoneservice=no',
 'phoneservice=yes',
 'seniorcitizen',
 'streamingmovies=no',
 'streamingmovies=no_internet_service',
 'streamingmovies=yes',
 'streamingtv=no',
 'streamingtv=no_internet_service',
 'streamingtv=yes',
 'techsupport=no',
 'techsupport=no_internet_service',
 'techsupport=yes',
 'tenure',
 'totalcharges']

#### 3.9 Machine learning for classification: Logistic regression
____

In [361]:
# importing the model
from sklearn.linear_model import LogisticRegression

In [362]:
# fitting the model
model = LogisticRegression(solver='liblinear', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1, solver='liblinear')

In [363]:
# model intercept
model.intercept_[0]

-0.1309373568620955

In [364]:
# model coef
model.coef_[0].round(3)

array([ 0.573, -0.166, -0.538, -0.016, -0.114,  0.076, -0.114, -0.093,
       -0.026, -0.105, -0.353,  0.336, -0.114,  0.001, -0.171,  0.112,
       -0.072,  0.12 , -0.114, -0.137,  0.263, -0.114, -0.28 , -0.207,
        0.076, -0.107, -0.024, -0.056, -0.116,  0.208, -0.167,  0.112,
       -0.243,  0.251, -0.099, -0.114,  0.081, -0.094, -0.114,  0.077,
        0.203, -0.114, -0.22 , -0.065,  0.   ])

In [371]:
# model prediction
y_pred = model.predict_proba(X_val)
y_pred

array([[0.76799864, 0.23200136],
       [0.75226365, 0.24773635],
       [0.72286717, 0.27713283],
       ...,
       [0.99773197, 0.00226803],
       [0.87742222, 0.12257778],
       [0.99855877, 0.00144123]])

In [373]:
# model prediction focusing on the soft prediction
y_pred = model.predict_proba(X_val)[:, 1]
y_pred

array([0.23200136, 0.24773635, 0.27713283, ..., 0.00226803, 0.12257778,
       0.00144123])

In [366]:
# setting the threshold to 0.5
churn_decision = (y_pred >= 0.5)

In [375]:
# checking the accuracy of the model
(y_val == churn_decision).mean()

0.7991483321504613

In [374]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = churn_decision.astype(int)
df_pred['actual'] = y_val

In [376]:
df_pred

      probability  prediction  actual
0        0.232001           0       0
1        0.247736           0       1
2        0.277133           0       0
3        0.355824           0       1
4        0.053981           0       0
...           ...         ...     ...
1404     0.028544           0       0
1405     0.786681           1       0
1406     0.002268           0       0
1407     0.122578           0       0
1408     0.001441           0       0

[1409 rows x 3 columns]

In [379]:
df_pred['correct'] = df_pred.prediction == df_pred.actual
df_pred

      probability  prediction  actual  correct
0        0.232001           0       0     True
1        0.247736           0       1    False
2        0.277133           0       0     True
3        0.355824           0       1    False
4        0.053981           0       0     True
...           ...         ...     ...      ...
1404     0.028544           0       0     True
1405     0.786681           1       0    False
1406     0.002268           0       0     True
1407     0.122578           0       0     True
1408     0.001441           0       0     True

[1409 rows x 4 columns]

In [378]:
df_pred.correct.mean()

0.7991483321504613